#!/usr/bin/env python3

# Cheeky .mem file creator.

import sys
import numpy as np

if __name__=='__main__':
    with open(sys.argv[1], 'rb') as fi, open(sys.argv[2], 'w') as fo:
        ai = np.fromfile(fi, dtype=np.uint16)
        fo.writelines('%04X\n' % x for x in ai)
